sys_includes = ["sys/types.h", "stdint.h", "sys/time.h"]
include_guard = "_SYS_RESOURCE_H"
trailer = "#include <bits/sys/resource.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"

[enum]
prefix_with_name = true

[export.rename]
"timeval" = "struct timeval"
