sys_includes = ["sys/ioctl.h"]
include_guard = "_RELIBC_SGTTY_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[export.rename]
"sgttyb" = "struct sgttyb"

[enum]
prefix_with_name = true
