sys_includes = ["sched.h", "time.h", "bits/pthread.h", "features.h"]
include_guard = "_RELIBC_PTHREAD_H"
language = "C"
style = "tag"
no_includes = true
cpp_compat = true

[export.rename]
"sched_param" = "struct sched_param"

[enum]
prefix_with_name = true
