sys_includes = ["stdarg.h", "stddef.h", "stdint.h", "sys/types.h"]
include_guard = "_STDIO_H"
trailer = "#include <bits/stdio.h>"
language = "C"

[enum]
prefix_with_name = true

[export.rename]
"AtomicBool" = "volatile char"
