sys_includes = ["stddef.h", "stdint.h", "sys/types.h"]
include_guard = "_SYS_SOCKET_H"
trailer = "#include <bits/sys/socket.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"

[enum]
prefix_with_name = true
