sys_includes = ["bits/ctype.h", "features.h"]
include_guard = "_RELIBC_CTYPE_H"
after_includes = "#include <bits/locale-t.h> // for locale_t"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
