sys_includes = ["sys/types.h", "bits/sched.h"]
include_guard = "_RELIBC_SCHED_H"
after_includes = """
#include <bits/time.h> // for timespec
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
