sys_includes = ["sys/types.h", "features.h", "sys/select.h"]
include_guard = "_SYS_TIME_H"
language = "C"
after_includes = """
#include <bits/time.h> // for timespec
#include <bits/sys/time.h>
"""
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"timespec" = "struct timespec"
"timeval" = "struct timeval"
