# POSIX header spec: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/errno.h.html
#
# There are no spec quotations relating to includes
sys_includes = ["bits/errno.h"]
include_guard = "_RELIBC_ERRNO_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
