sys_includes = ["sys/types.h"]
include_guard = "_RELIBC_DIRENT_H"
language = "C"
style = "Both"
trailer = "#include <bits/dirent.h>"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
