sys_includes = ["stdint.h", "wchar.h"]
include_guard = "_RELIBC_INTTYPES_H"
trailer = "#include <bits/inttypes.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
