sys_includes = ["sys/types.h", "stdint.h", "stddef.h", "features.h"]
include_guard = "_RELIBC_TIME_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true
after_includes = """
struct sigevent;
"""

[enum]
prefix_with_name = true

[export.rename]
"sigevent" = "struct sigevent"
