sys_includes = ["sys/types.h", "stdint.h", "stddef.h"]
include_guard = "_TIME_H"
language = "C"
style = "Tag"

[enum]
prefix_with_name = true

[defines]
"target_os = linux" = "__linux__"
"target_os = redox" = "__redox__"
