sys_includes = ["stddef.h", "alloca.h"]
include_guard = "_RELIBC_STDLIB_H"
trailer = "#include <bits/stdlib.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
