sys_includes = ["sys/types.h"]
include_guard = "_SYS_STAT_H"
after_includes = """
#include <bits/time.h> // for timespec
#include <bits/sys/stat.h>
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
