sys_includes = ["signal.h"]
include_guard = "_RELIBC_POLL_H"
after_includes = """
#include <bits/time.h> // for timespec
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
