# no default C includes - they cause recursive dependencies and do weird stuff
no_includes = true
sys_includes = [
    # Import most necessary, internal types first
    "sys/types_internal.h",

    "stddef.h",
    "sys/select.h"
]

include_guard = "_SYS_TYPES_H"
language = "C"
style = "Tag"

[enum]
prefix_with_name = true
