[package]
name = "wait"
version = "0.1.0"
authors = ["Dan Robertson <danlrobertson89@gmail.com>"]

[build-dependencies]
cbindgen = { path = "../../cbindgen" }

[dependencies]
platform = { path = "../platform" }
resource = { path = "../resource" }
