sys_includes = ["stddef.h", "stdint.h", "time.h", "stdio.h" ]
include_guard = "_RELIBC_WCHAR_H"
header = "#include <bits/wchar.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
