sys_includes = []
include_guard = "_RELIBC_SEMAPHORE_H"
after_includes = """
#include <bits/time.h> // for timespec
"""
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
