sys_includes = ["stdarg.h", "stddef.h", "stdint.h", "sys/types.h"]
include_guard = "_RELIBC_STDIO_H"
trailer = "#include <bits/stdio.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"AtomicBool" = "volatile char"
