sys_includes = ["stddef.h", "stdint.h", "sys/types.h"]
include_guard = "_RELIBC_UNISTD_H"
trailer = "#include <bits/fcntl.h>\n#include <bits/unistd.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[defines]
"target_os = linux" = "__linux__"
"target_os = redox" = "__redox__"
