sys_includes = ["stddef.h", "stdint.h", "sys/types.h", "features.h"]
include_guard = "_RELIBC_UNISTD_H"
trailer = """
#include <bits/unistd.h>
"""
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true
