sys_includes = ["sys/types.h", "stdint.h", "features.h"]
include_guard = "_RELIBC_TERMIOS_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[export.rename]
"winsize" = "struct winsize"
