sys_includes = ["stdint.h", "sys/types.h"]
include_guard = "_SIGNAL_H"
style = "Tag"
language = "C"

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"

[enum]
prefix_with_name = true
